apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{.Values.service.name}}
spec:
  replicas: {{.Values.deploy.replica}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}/my_image"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
      #for pull image from aws ecr
      imagePullSecrets:
      - name: regcred         