---
- name: Check k8s and CRI-O installed
  shell: dpkg -s kubelet
  register: rc_k8s
  ignore_errors: true  

- name: Install k8s and CRIO on master and workers
  block:
  - name: Prepare for install 1
    blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter
      create: true

  - name: Prepare for install 2
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: Prepare for install 3
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      block: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
      create: true

  - name: Prepare for install 4
    shell: sudo sysctl --system  

  - name: Install dependencies for adding the repositories
    shell: |
      apt-get update
      apt-get install -y software-properties-common curl

  - name: Install packages needed to use k8s repository
    shell: apt-get install -y apt-transport-https ca-certificates      

  - name: Add repository k8s
    shell: |
      mkdir -p /etc/apt/keyrings
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list

  - name: Add repository CRIO
    shell: |
      curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
      echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /" | tee /etc/apt/sources.list.d/cri-o.list

  - name: Install k8s and CRIO
    shell: |
      apt-get update
      apt-get install -y cri-o kubelet kubeadm kubectl

  - name: Start CRI-O
    shell: systemctl start crio
  when: rc_k8s.rc != 0