---
- name: Deploy web page(run in master)
  block:
  - name: Copy files to master from localhost to deploy all
    copy:
      src: helm/web
      dest: $HOME/helm

  - name: Install Cert-manager
    shell: |
      helm repo add jetstack https://charts.jetstack.io
      helm repo update
      helm upgrade --install cert-manager jetstack/cert-manager \
        --namespace cert-manager --create-namespace --version v1.13.1 \
        --set installCRDs=true 
    #  --set webhook.hostNetwork=true --set webhook.securePort=10260
    ignore_errors: true    

  - name: Generate values.yaml
    template: 
      src: values.j2
      dest: $HOME/helm/web/values.yaml

  - name: Delete secret key for pull image(if it exist)
    shell: kubectl delete secret regcred --ignore-not-found -n my-project

  - name: Create secret for pull image
    shell: |
      kubectl create namespace my-project
      kubectl create secret docker-registry regcred --docker-username=AWS \
        --docker-server={{ aws_user_id_from_terraform }}.dkr.ecr.{{ region_from_terraform }}.amazonaws.com \
        --docker-password=$(aws ecr get-login-password --region {{ region_from_terraform }}) -n my-project

  - name: Run deploy and service
    shell: |
      cd helm/web/
      while ! helm upgrade --install -n my-project --create-namespace test .; do sleep 5; done
    #will run unless success(until Ingress-Nginx Controller starts)
  become: false
  #if run with become: true(in ansible.cfg) then %HOME will be /root and all run will be as root  
  when: "'ansible_master' in group_names"      