---
- name: Deploy web page(run in master)
#if run with become: true(in ansible.cfg) then %HOME will be /root and all run will be as root
  block:
  - name: Copy files to master from localhost to deploy web page
    become: false
    copy:
      src: web
      dest: $HOME

  - name: Copy aws credentials to master
    become: false
    copy:
      src: .aws/
      dest: ~/.aws/

  - name: Install AWS CLI
    shell: apt install -y awscli

  - name: To log in to an Amazon ECR registry
    become: false
    shell: aws ecr get-login-password --region {{ region_from_terrafrom }} | podman login --username AWS \
            --password-stdin 728490037630.dkr.ecr.{{ region_from_terrafrom }}.amazonaws.com
    
  - name: Build image
    become: false
    shell: podman build web/nginx_phpfpm/src/ -t 728490037630.dkr.ecr.{{ region_from_terrafrom }}.amazonaws.com/my_image

  - name: Push image
    become: false
    shell: podman push 728490037630.dkr.ecr.{{ region_from_terrafrom }}.amazonaws.com/my_image 

  - name: Create secret for pull image
    shell: |
      kubectl create secret docker-registry regcred --docker-username=AWS \
      --docker-server=728490037630.dkr.ecr.eu-north-1.amazonaws.com --docker-password=$(aws ecr get-login-password --region eu-north-1)
  - name: Run deploy and service
    shell: |
      cd web/helm_chart/helm/templates
      kubectl apply -f deploy-nginx1.yaml
      kubectl apply -f service-nginx1.yaml
  when: "'ansible_master' in group_names"       