---
- name: Run in workers
  block:
  - name: Create directory
    become: false
    file:
      path: $HOME/.kube/
      state: directory
      mode: '0755'
  
  - name: Copy config to workers from localhost for workers 
    become: false
    copy:
      src: config
      dest: $HOME/.kube/config
  
  - name: Need before join workers
    shell: yes | sudo kubeadm reset

  - name: Init workers(role_path - system variable)
    script: "{{ role_path }}/files/join_for_workers.sh"
  when: "'ansible_workers' in group_names"