apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  generation: 1
  name: issuer-letsencrypt
spec:
  acme:
    email: FatherFedor13@gmail.com
    privateKeySecretRef:
      name: issuer-letsencrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
