apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssl-dev
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "issuer-letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: ssl-letsencrypt 
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sv-nginx
              port:
                number: 80