apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssl-dev
  #namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "issuer-letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /

  #  kubernetes.io/ingress.class: nginx 
  #  kubernetes.io/tls-acme: "true"
  #  nginx.ingress.kubernetes.io/tls-acme: "true"
  #  acme.cert-manager.io/http01-edit-in-place: "true"
  #  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  #  nginx.ingress.kubernetes.io/proxy-body-size: 100m
  #  nginx.ingress.kubernetes.io/permanent-redirect: https://$host$request_uri
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "nginx.fatherfedor.shop"
      secretName: ssl-letsencrypt 
  rules:
    - host: "nginx.fatherfedor.shop"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sv-nginx
              port:
                number: 80