apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssl-dev
  #namespace: {{.Values.namespace}}
  #{{- with .Values.ingress.annotations }}  
  #annotations:
  #  {{- toYaml . | nindent 4 }}
  #{{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "nginx.fatherfedor.shop"
      secretName: issuer-letsencrypt 
  rules:
    - host: "nginx.fatherfedor.shop"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sv-nginx
              port:
                number: 80