apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-letsencrypt
spec:
  acme:
    email: FatherFedor13@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory    
    privateKeySecretRef:
      name: issuer-letsencrypt
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
