{
 "title": "MyDash",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds{job=\"node-exporter\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "expr": "time()", "legendFormat": "__auto" }
   ]
  },
  { "type": "canvas", "gridPos": { "h": 2, "w": 13, "x": 3, "y": 0 } },
  {
   "title": "CPU Busy %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{node=\"$Node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',node=\"$Node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{node=\"$Node\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Avg 1m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{node=~\"$Node\"}) / count(count(node_cpu_seconds_total{node=~\"$Node\"}) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{node=\"$Node\"} - node_memory_MemFree_bytes{node=\"$Node\"}) / (node_memory_MemTotal_bytes{node=\"$Node\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=\"$Node\",fstype=\"ext4\"} * 100) / node_filesystem_size_bytes{node=\"$Node\",fstype=\"ext4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nginx.fatherfedor.shop",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"deploy-sv-nginx\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=\"deploy-sv-nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry-time()",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}