apiVersion: v1
#{{ "{{" }} - because deploying via a helm chart. It will be only 2 brackets after helm
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  alert.yml: |
    groups:
    - name: alert down
      rules:  
      - alert: blackbox-alert
        expr: probe_success{instance="https://prefix.domain"} == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          title: "https://prefix.domain is down"
          summary: https://prefix.domain job missing (instance {{ "{{" }} $labels.instance {{ "}}" }}) VALUE = {{ "{{" }} $value {{ "}}" }} LABELS = {{ "{{" }} $labels {{ "}}" }}
          description: "https://prefix.domain doesn't return any metrics. The site might be crashed."